# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa20512204268cf677e0877430cbfc7f40ec957450b5ef33fbaa6f375272942006f95f140ac1715dd920ab5d48d761016e30eaa9c9a216f1cffa8c2d0a7d8f28

test:
  secret_key_base: a934be10d561f5a13ef34b86e007681de99525db565f4e60a4b73627603064da831a046d837bfa63f2e7c98a1671348b98ee57f9c50c45427c3139ec94442388

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
